title: 'AUTONOMED'
baseURL: 'https://autonomed.cl'
languageCode: 'es-cl'

params:
  description: 'Investigación sobre ecosistemas de medios nativos digitales en Chile'
  author: 'Equipo AUTONOMED'
  
  # Social
  twitter: 'autonomed_cl'
  github: 'renejara-hub'
  email: 'contacto@autonomed.cl'
  
  # Footer
  copyright: '© 2025 AUTONOMED - Ecosistemas de Medios Digitales Chile'
